
GET http://localhost:5000/states/
###

GET http://localhost:5000/states/34/
###

POST http://localhost:5000/districts/

{
    "districtName":"Bagalkot",
    "stateId":3,
    "cases":2323,
    "cured":2000,
    "active":315,
    "deaths":8
}
###

GET http://localhost:5000/districts/311/
###

DELETE http://localhost:5000/districts/322/
###

PUT http://localhost:5000/districts/311/

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:5000/states/32/stats/
###

GET http://localhost:5000/districts/20/details/